# Generated by Django 4.2.1 on 2023-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='special_request',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='data_time',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='profession',
            field=models.CharField(default='manager', max_length=30),
        ),
    ]
