# Generated by Django 4.2.1 on 2023-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_name_alter_comment_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='img/testimonial-1.jpg', upload_to='pics'),
        ),
    ]
