# Generated by Django 4.2.1 on 2023-06-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_comment_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
